### ISSUE TITLE
Trading bug; items become your's without paying when you r-click drop items from a trader

### ISSUE THREAD

**Issue by Oskutin** [loiste-interactive/Open-Sewer-Issues#274]

**Comment by Oskutin** [comment]
This is now fixed, not perfect, but ductaped, yes.

**Comment by Z-O-M-B-I-E** [comment]
I had such a bug, once it worked so that the merchant paid me for his own items (3000 OC), and the second time he gave me the items for free.
![20190117153609_1](https://user-images.githubusercontent.com/46783282/51319556-700aee00-1a6e-11e9-93ec-b0f64aaf658b.jpg)
![20190117153620_1](https://user-images.githubusercontent.com/46783282/51319557-70a38480-1a6e-11e9-8ffe-e1c242081139.jpg)
![20190117075928_1](https://user-images.githubusercontent.com/46783282/51319574-7dc07380-1a6e-11e9-8a76-d87eff8323b8.jpg)

**Comment by Z-O-M-B-I-E** [comment]
Video: https://www.youtube.com/watch?v=zLfJoNx22c4

**Comment by Z-O-M-B-I-E** [comment]
And video 2, money boost: https://www.youtube.com/watch?v=lAITIvKpIII
